### PR TITLE
Added normalize functionality

### PR DESCRIPTION
**Pull request by alv-c**
Added the normalize functionality.

The normalize functionality works like this.

1- Save the untransformed text when user clicks on any transformation method.
2- Set the input value to that saved value when user clicks "normalize" (in case there is any untrasformed text).

Limitations with my method of normalizing text.

You cannot normalize any pasted text; actually, you cannot normalize any text that you didn't write manually.

Now that I'm writing this I came to realize that this is no different from having untransformed text saved in clipboard.

Nvm, I'm doing pull request anyway

### CODE REVIEW

**Comment by guitarxhero** [comment]
That was _not_ the intention of the Normalize function. It was to simply revert back the input text to normal text (e.g. Ｈｅｌｌｏ to Hello), based on the stop-and-go philosophy, since I never expect anyone to do more than one transformation.

**Comment by guitarxhero** [comment]
Though with your functionality, that would be called _Revert_, since there are changes that are saved in memory.

**Comment by alv-c** [comment]
Yeah, I've realized that just when I opened this pull request.
I may keep playing with this then.

**Comment by guitarxhero** [comment]
I would simply continue what I was doing.

**Comment by alv-c** [comment]
Are you talking about you or about me?

**Comment by guitarxhero** [comment]
I would (in your case), continue where I (myself) was going

**Pull request closed without merging**
